site_name: Xdd的帮助系统
theme:
  name: material
  palette:
    primary: 'green'
plugins:
    - search:
        lang:
            - en
            - ja
        separator: '[\s\-\.]+'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/xie-dd/mkdocs'
    - type: '博客'
      link: 'https://19970622.xyz'

